# Basics of PyTorch


In [1]:
# Standard Libraries
import os
import math
import numpy as np
import time

# Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline

# Progress bar
from tqdm import tqdm

In [2]:
# Import torch
import torch
print(f"Using torch, {torch.__version__}")

Using torch, 2.11.0+cu128


In [3]:
# Set the random number seed for reproducibility
torch.manual_seed(42)

In [5]:
# Tensors are pytorch equivalent to numpy with additional support for GPU accelaration.
# They are generalization of a vector or a matrix.


In [46]:
# Tensor Initialization
# This creates a tensor of shape 2 x 2, with random/garbage values.
# Not recomended for initialization.

x = torch.Tensor(2,2)
print(x)


tensor([[2.6218e+10, 3.2125e-41],
        [4.4264e+15, 3.2125e-41]])


In [47]:

## Using torch.zeros
# Here we specify shape/dimensions only as arguments & pytorch creates data automatically.

In [60]:
x = torch.zeros(3)
print(x)
print(x.shape)
# This creates a 1D vector with 3 elements
# Shape: (3)
# One axis with 3 elements

tensor([0., 0., 0.])
torch.Size([3])


In [50]:
x = torch.zeros((1,3))
print(x)
print(x.shape)
# Creates a 2D tensor (matrix)
# Shape: (1,3)
# 1 row and 3 columns

tensor([[0., 0., 0.]])
torch.Size([1, 3])


In [51]:
x = torch.zeros((2,3))
print(x)
print(x.shape)
# Creates a 2D tensor (matrix) with 2 rows and 3 columns/elements

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [52]:
x = torch.zeros((2,3,2))
print(x)
print(x.shape)
# This creates a 3Dtensor with 2 blocks, 
# each block with 3 rows and
# each row with 2 elements/columns

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.Size([2, 3, 2])


In [62]:
# Create a tensor from a nested list
x = torch.tensor([0.,0.,0.])
x.size()
# Here We explicitly gave values, and pytorch infers shape from the nesting structure

torch.Size([3])

In [64]:
x = torch.tensor([[0.,0.,0.]]) # 2D tensor
x.size()

torch.Size([1, 3])

In [73]:
x = torch.tensor(
 # list
[
[     # Block 0
    
[0,0,0,0], # Row 0
[0,0,0,0], # Row 1
[0,0,0,0]  # Row 2

],

[    # Block 1

[0,0,0,0],
[0,0,0,0],
[0,0,0,0]

]
]   

)
x.shape


torch.Size([2, 3, 4])

In [70]:
x = torch.rand(2,3,4)

x.shape

torch.Size([2, 3, 4])

In [81]:
# Create a tensor with random values between 0 and 1 with shape (2,3,4)
x = torch.rand(2,3,4)
x

tensor([[[0.4137, 0.6044, 0.7581, 0.9037],
         [0.9555, 0.1035, 0.6258, 0.2849],
         [0.4452, 0.1258, 0.9554, 0.1330]],

        [[0.7672, 0.6757, 0.6625, 0.2297],
         [0.9545, 0.6099, 0.5643, 0.0594],
         [0.7099, 0.4250, 0.2709, 0.9295]]])

In [83]:
# Create a tensor with normally distributed  values with mean 0  and sigma 1 with shape (2,3,4)
x = torch.randn(2,3,4)
x    

tensor([[[-0.8146, -1.0212, -0.4949, -0.5923],
         [ 0.1543,  0.4408, -0.1483, -2.3184],
         [-0.4611, -0.0639, -1.3667,  0.3298]],

        [[-0.9827,  0.3018,  0.1787, -0.1293],
         [-1.5754,  2.2508,  1.0012,  1.3642],
         [ 0.6333,  0.4050,  0.3416, -0.2214]]])

In [80]:
# Create Identity Matrix of size (3x3)
x = torch.eye(3)
x
# A 2-D tensor with ones on the diagonal and zeros elsewhere 
# by default # columns m is same as # rows 'n'
x = torch.eye(3,5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [88]:
x = torch.arange(0,5,1)
# Creates a 1D tensor of size 5 start 0, end: 4 and step size is 1
x

tensor([0, 1, 2, 3, 4])

# Numpy to Tensor and vise-versa

In [93]:
np_arr = np.array([1,2,3]) # One axis 3 elements
np_arr.shape

(3,)

In [94]:
tensor = torch.from_numpy(np_arr)
print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)
# Note numpy prints array w/o ',' like more mathematical and matrix like style,
# while torch prints it like  python container (list)

Numpy array: [1 2 3]
PyTorch tensor: tensor([1, 2, 3])


In [16]:
# Try a 2D tensor
np_arr = np.array([[1,2],[3,4]])
print(np_arr.shape)
print(np_arr)
tensor = torch.from_numpy(np_arr)
print(tensor.shape)
print(tensor)

(2, 2)
[[1 2]
 [3 4]]
torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [12]:
# Transform back tensor to numpy array using .numpy()
np_arr2 = tensor.numpy()
np_arr2

array([[1, 2],
       [3, 4]])

# How is tensor is saved on memory: Strides

In [12]:
# How is a tensor stored in memory
x = torch.tensor([[1,2,3],[4,5,6]])

# Even though the shape of the tenosr is (2,3)
# PyTorch stores the data as flat 1D block of memory:
# For ex:
# Memory position:  0  1  2  3  4  5
# Value:            1  2  3  4  5  6

# PyTorch uses meta data to interpert the block of memory as a 2x3 tensor

print(x.shape) # torch.Size([2, 3])
print(x.stride()) # (3, 1)
print(x.is_contiguous()) # True

# The stride tells us to jump that many location in memory to go to next column or row.
# Here if u jump 1 memory location u get x[0,1] = 2, then again 1 jump gives x[0,2] = 3 etc..
# 3 jumps & u go to next row: x[0,3] = 4.
#
# Move down a row → jump 3
# Move right a column → jump 1

# In general:
# x[i,j] = i * stride[0] + j * stride[1] 
# x[1,1] = 1 * 3 + 1 * 1 = 4
# Memory location 4 contains 5, so x[1,1] = 5 
print(x[1,1])

torch.Size([2, 3])
(3, 1)
True
tensor(5)


In [19]:
# Thus a tensor is basically data + shape + stride

# Now, Lets take transpose of x:

y = x.t() #torch.tensor([[1,4],[2,5],[3,6]])
print(y.shape) # torch.Size([3, 2])
print(y.stride()) # (1, 3)
print(y.is_contiguous()) # False
print(y)

# y[0,0]:
# offset = 0*1 + 0*3 = 0
# memory[0] = 1
#
# y[0,1]:
# offset = 0*1 + 1*3 = 3
# memory[3] = 4
#
# y[1,0]:
# offset = 1*1 + 0*3 = 1
# memory[1] = 2
#
# y[1,1]:
# offset = 1*1 + 1*3 = 4
# memory[4] = 5
#
# y[2,0]:
# offset = 2*1 + 0*3 = 2
# memory[2] = 3
#
# y[2,1]:
# offset = 2*1 + 1*3 = 5
# memory[5] = 6


# As u will see taking transopse doesnt actually change storage, only shape and stride is changed.
# since x and y share the SAME memory:

y[0,1] = 100
# Thus 1st row , 2nd element to changes to 100, 
# but also x is affected since they share same memory:
print("\nAfter y[0,1] = 100")

print("\nx:")
print(x)

print("\ny:")
print(y)

# So y[0,1] = 0 * y_stride[0] + 1 * y_stride[1]
#            = 3
# Thus Memory location 3 is now 100.
# Position: 0   1   2   3   4   5
# Value:    1   2   3   100  4  5

# Thus now 

# So x[i,j] = i * x_stride[0] + j * x_stride[1]
#            = 3 * i + j = 3
#            => i = 0 and j = 3
#            => i = 1 and j = 0

# x[0,3] = 3 (Outside limit)
# x[1,0] = 3 = Memowry(3) = 100
# Thus x[1,0] = 100


torch.Size([3, 2])
(1, 3)
False
tensor([[  1, 100],
        [  2,   5],
        [  3,   6]])

After y[0,1] = 100

x:
tensor([[  1,   2,   3],
        [100,   5,   6]])

y:
tensor([[  1, 100],
        [  2,   5],
        [  3,   6]])


In [28]:
z = x.view(6)
print(z.shape)
print(z.stride())
print(z.is_contiguous())
print(z)


torch.Size([6])
(1,)
True
tensor([  1,   2,   3, 100,   5,   6])


In [36]:
#y.view(6) # Fails bcoz y is non-contiguous
# Logically we want this to be [1,4,2,5,3,6] since y = x.t()...
# But in memory we have [1,2,3,4,5,6]
# For y.view(6), the stride is 1 (1D tensor)
# => In memory we are allowed to move 1 unit to produce y. 
# Since in order to produce y like [1,4,2,5,3,6]
# We might need to move/jump [0,3,1,4,2,5] to get y from x,
# which is not possible with stride 1.
# Therefore view() cannot create y.view(6) without rearranging/copying data,
# and view() is not allowed to rearrange memory.
# Even y.view(2,3) fails !!
# Summary:
# View asks like can the requested tensor be represented
# using the same storage and a valid stride pattern?

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [37]:
# reshape(6) works because it can allocate new memory and copy the data.
z = y.reshape(6)
print(z.size)
print(z.stride())
print(z.is_contiguous())
print(z)


<built-in method size of Tensor object at 0x72ff2b49e120>
(1,)
True
tensor([  1, 100,   2,   5,   3,   6])


# Molding a Tensor  Only changes shape

In [6]:
# Use .view() to change the shape of a tensor to any shape with same number of total elements:
# For example, a tensor with 6 elements can be viewed
# as (2,3), (3,2), (1,6), (6,1), etc.

x = torch.arange(6)
print(x.shape)
print(x.stride())
print(x.is_contiguous())

# .view() does NOT modify x in-place.
# Since the result is not assigned, x remains unchanged.
x.view(2,3) 
print("x ",x)
print(x.shape)
print(x.stride())
print(x.is_contiguous())



x = x.view(2,3) # Store the returned view
print("x ",x)
print(x.shape)
print(x.stride())
print(x.is_contiguous())

# Different valid views of the same 6 elements
x = x.view(3,2)
print("x ",x)

x = x.view(1,6)
print("x ",x)

x = x.view(6,1)
print("x ",x)


# x = x.view(3,3)
# print("x ",x)
# Throws error since 3x3 = 9 doesnt match total number of elements 6.

# Original tensor contains 6 elements
# Requested shape requires 3×3 = 9 elements
#
# Number of elements must always be preserved

# Important:
# .view() only changes how we interpret the data.
# It does NOT reorder or copy the underlying memory.
#
# Therefore .view() is very fast.
#
# Since the memory is shared, modifying the view
# will also modify the original tensor.

torch.Size([6])
(1,)
True
x  tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])
(1,)
True
x  tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
(3, 1)
True
x  tensor([[0, 1],
        [2, 3],
        [4, 5]])
x  tensor([[0, 1, 2, 3, 4, 5]])
x  tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


# Indexing and Slicing

In [36]:
# Indexing selects specific elements, rows, columns, or blocks.
# ':' means "select all elements along that axis".
# Integer indexing removes the selected axis:
#     x[:,1]   -> shape (3,)
# Slicing preserves the axis:
#     x[:,1:2] -> shape (3,1)
# Rule: integer index removes an axis, slice preserves it.

In [37]:
x = torch.arange(12).view(2,2,3) # Example of a  3D tensor
print("x", x)
print(x.stride())

x tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
(6, 3, 1)


In [38]:
print(x[:,1,:]) # All blocks, row 1, all elements
print(x[:,1,:].shape) # (2,3)

# Original shape: (2,2,3)
#                 ^ ^ ^
#              block row element
#
# We fixed the row axis using integer indexing (1),
# so that axis is removed.
#
# Remaining axes:
#   block   -> size 2
#   element -> size 3
#
# Resulting shape: (2,3)

# Note here we get shape (2,3) since selecting 2nd row from both the block we loose that axis. 
# so the shape is 2 for blocks and 3 for elements

tensor([[ 3,  4,  5],
        [ 9, 10, 11]])
torch.Size([2, 3])


In [39]:
print(x[:,:,0])
print(x[:,:,0].shape)

# Here again we select 1st element from all rows in each block. But we loose that dimension/axis since we use integer slicing
# so size is (2,2)
# To preserve that dimension:
print(x[:,:,0:1])
print(x[:,:,0:1].shape)
# Shape = (2,2,1)
#
# Here 0:1 is a slice, not an integer index.
# Slicing preserves the axis, so the element axis
# remains with size 1.

tensor([[0, 3],
        [6, 9]])
torch.Size([2, 2])
tensor([[[0],
         [3]],

        [[6],
         [9]]])
torch.Size([2, 2, 1])


In [40]:
x = torch.arange(12).view(3,4)
print("x", x)
print(x.stride())
print(x[:,1].shape)    # (3,)
print(x[:,1:2].shape)  # (3,1)

x tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
(4, 1)
torch.Size([3])
torch.Size([3, 1])


In [43]:
# Second column
print(x[:,1]) # (3,4) => (3,)

tensor([1, 5, 9])


In [45]:
# First row
print(x[0,:])
print(x[0,:].shape)

tensor([0, 1, 2, 3])
torch.Size([4])


In [47]:
# First two rows, last column
print(x[0:2,-1])
print(x[0:2,-1].shape)


tensor([3, 7])
torch.Size([2])


# Mathematical Operations

In [4]:
# Addition of two tensors
a = torch.rand(2,3)
b = torch.rand(2,3)
c = a + b
print("a =", a)
print("b =", b)
print("c =", c)

# Using in-place operations that can be applied directly on the tensor, thus modifiying it..
b.add_(a)
print(b)


a = tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
b = tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
c = tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])
tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])


In [6]:
# Matrix Multiplication
torch.matmul??

Docstring:
matmul(input, other, *, out=None) -> Tensor

Matrix product of two tensors.

The behavior depends on the dimensionality of the tensors as follows:

- If both tensors are 1-dimensional, the dot product (scalar) is returned.
- If both arguments are 2-dimensional, the matrix-matrix product is returned.
- If the first argument is 1-dimensional and the second argument is 2-dimensional,
  a 1 is prepended to its dimension for the purpose of the matrix multiply.
  After the matrix multiply, the prepended dimension is removed.
- If the first argument is 2-dimensional and the second argument is 1-dimensional,
  the matrix-vector product is returned.
- If both arguments are at least 1-dimensional and at least one argument is
  N-dimensional (where N > 2), then a batched matrix multiply is returned.  If the first
  argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the
  batched matrix multiply and removed after.  If the second argument is 1-dimensional, a


In [11]:
# vector x vector = dot product (scalar)
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
result = torch.matmul(tensor1,tensor2)
print(result)
print(result.size())
# Rule: (n,) @ (n,) = scalar()

tensor(0.0264)
torch.Size([])


In [23]:
# vector x matrix
vector1 = torch.arange(3) # Shape: (3) neither a row nor a column
matrix1 = torch.arange(6).view(3,2) # Shape: (3,2)
result = torch.matmul(vector1,matrix1)  # (1 x 3) @ (3 x 2) = (1 x 2) = (2)
print(vector1.shape)
print(matrix1.shape)
print(result.shape)


torch.Size([3])
torch.Size([3, 2])
torch.Size([2])


In [24]:
torch.unsqueeze?? # Adds a dimension of size 1 at specified position
# x.shape == (3,)      # 1D vector, no rows, no column
# x.unsqueeze(0)       # row vector-like: (1,3)
# x.unsqueeze(1)       # column vector-like: (3,1)
# squeeze()	(1,3,1,4) → (3,4)	Remove all size-1 dimensions

Docstring:
unsqueeze(input, dim) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.

The returned tensor shares the same underlying data with this tensor.

A :attr:`dim` value within the range ``[-input.dim() - 1, input.dim() + 1)``
can be used. Negative :attr:`dim` will correspond to :meth:`unsqueeze`
applied at :attr:`dim` = ``dim + input.dim() + 1``.

Args:
    input (Tensor): the input tensor.
    dim (int): the index at which to insert the singleton dimension

Example::

    >>> x = torch.tensor([1, 2, 3, 4])
    >>> torch.unsqueeze(x, 0)
    tensor([[ 1,  2,  3,  4]])
    >>> torch.unsqueeze(x, 1)
    tensor([[ 1],
            [ 2],
            [ 3],
            [ 4]])
Type:      builtin_function_or_method

In [29]:
vector1 = torch.arange(3)
print(vector1.shape)
vector1 = vector1.unsqueeze(0)
print(vector1.shape)


torch.Size([3])
torch.Size([1, 3])


In [32]:
matrix = torch.arange(9).view(3,3)
matrix = matrix.unsqueeze(1)
matrix.shape


torch.Size([3, 1, 3])

In [44]:
# matrix x vector
matrix1 = torch.arange(1,13).view(4,3)
vector1 = torch.arange(3) # => transformed to column like vector using unsqueeze(1)
result = torch.matmul(matrix1,vector1) # (4 x 3) @ (3 x 1) = 4 x 1,then squeeze(1) = 4
print(result.size())
print(matrix1)
print(vector1)
print(result)


torch.Size([4])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([0, 1, 2])
tensor([ 8, 17, 26, 35])


In [45]:
# Rules whenever 1D tensor is involved in matmul:
# input shapes	Result shape
# (m,n) @ (n,)	(m,)
# (m,n) @ (n,1)	(m,1)
# (n,) @ (n,m)	(m,)
# (1,n) @ (n,m)	(1,m)

In [47]:
# Matrix x Matrix
matrix1 = torch.arange(12).view(3,4)
matrix2 = torch.arange(8).view(4,2)
result = torch.matmul(matrix1,matrix2) 
result

# Rule: (m,n) @ (n,p) = (m,p)

tensor([[ 28,  34],
        [ 76,  98],
        [124, 162]])

In [23]:
# Element wise multiplication
#   [a,b,c] * [x,y,z]
# = [a*x, b*y, c*z]
#
# Shapes must be compatible.
# If shapes differ, PyTorch tries BROADCASTING.
#
# Broadcasting involves replicating smaller arrays to match the dimensions of larger ones during arithmetic operations.
# Rules: start from right, take first shape of both tensors, if same or if any is 1 then works else fails.
#       then check next shape towads left. If fewer dimension, adds 1. 
# (m,n) * (m,n) => (m,n)
# (m,n) * (n,) => right-align => (m,n) * (1,n) => works = (m,n)
# (m,n) * (m,) => right-align => (m,n) * (1,m) => fails (n vs m)
# (n,) * (m,n) => right-align => (1,n) * (m,n) => works = (m,n)
# (m,) * (m,n) => right-align =>  (1,m) * (m,n) =>failes (m vs n)
# (m,n) * (m,1) => works = (m,n) row-wise broadcast
# (m,n) * (1,n) => works = (m,n) column wise broadcast

matrix1 = torch.arange(6).view(2,3)
matrix2 = torch.arange(3)
result = matrix1 * matrix2
result.shape

# These rules apply to any arithmetic operations like  addition, subtraction, division, comparisons, etc.

torch.Size([2, 3])

In [22]:
# -----------------------------------------------------------------------------
# HIGHER DIMENSIONS
# -----------------------------------------------------------------------------
#
# (5,2,3) * (3,)
#
# Right-align:
#
# (5,2,3)
# (1,1,3)
#
# Compare:
#
# 3 vs 3 -> OK
# 2 vs 1 -> OK
# 5 vs 1 -> OK
#
# Result: (5,2,3)
#
# -----------------------------------------------------------------------------
#
# (4,5,2,3) * (5,1,3)
#
# Right-align:
#
# (4,5,2,3)
# (1,5,1,3)
#
# Compare:
#
# 3 vs 3 -> OK
# 2 vs 1 -> OK
# 5 vs 5 -> OK
# 4 vs 1 -> OK
#
# Result: (4,5,2,3)
#
# -----------------------------------------------------------------------------
# Memory Trick
# -----------------------------------------------------------------------------
#
# Always:
#
#   1. Right-align
#   2. Pad missing dimensions with 1s on the LEFT
#   3. Compare from RIGHT to LEFT
#   4. Equal or 1 -> OK
#   5. Otherwise -> ERROR
#
# =============================================================================

In [26]:
# NN use broadcsting for bias:
n_samples = 10
n_features = 3
feature_matrix = torch.arange(n_samples*n_features).view(n_samples,n_features) # (10,3)
# 1 hidden layer with 8 neurons
weights = torch.randn(n_features,8)
bias = torch.randn(8)
z = feature_matrix @ weights + bias # (10,3) @ (3,8) + (8) => (10,8) + (8) => right-align => (10,8) + (1,8) => bias broadcast(10,8)
# bias = [b1,b2,b3,b4,b5,b6,b7,b8]
# broadcast
# # bias = [
# [b1,b2,b3,b4,b5,b6,b7,b8], #1
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8],
# [b1,b2,b3,b4,b5,b6,b7,b8] # 10
# ]

# X : (10,3)
# W : (3,8)
# b : (8,)
# Z : (10,8)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]])

# Dynamic Computation Graph

In [36]:
# One of the main reasons for using PyTorch in deep learning is its
# automatic differentiation (autograd) system.

# During training, we usually define a loss/cost function and try to
# optimize the model parameters (weights and biases) by minimizing
# this loss.

# To update the parameters, we need to know how the loss changes
# with respect to small changes in each parameter, i.e. we need
# partial derivatives (gradients).

# A loss function is typically built from many operations:
# matrix multiplications, additions, activations, etc.

# As these operations are executed, PyTorch records them and builds
# a dynamic computation graph describing how every tensor was produced.

# During the backward pass, PyTorch applies the chain rule through
# this graph to automatically compute gradients.

# We only need to tell PyTorch which tensors should track gradients,
# typically the model parameters (weights and biases).

# This is done by setting:
#
#     requires_grad=True
#
# when creating the tensor.


In [37]:
# In order to get familiar with the concept of a computation graph, we will create one for the following function:


$$
y = \frac{1}{l(x)} \sum_{i} [ (x_{i}+2)^{2} + 3 ]
$$

In [117]:
# Lets first compute it ourselves:
# x = [0,1,2]

# a = x + 2
#  = [2,3,4]

# b = a^2
#  = [4,9,16]

# c = b + 3
#  = [7,12,19]

# y = mean(c)
#  = (7 + 12 + 19) / 3
#  = 38 / 3
#  = 12.6667

In [70]:
# Here we assume that x 's is our parametes. l(x) is its size
x = torch.arange(3,dtype=torch.float32,requires_grad=True)
print(x)

tensor([0., 1., 2.], requires_grad=True)


In [116]:
a = x + 2 
print(a.grad_fn)
print(a.grad_fn.next_functions) # no operations on x except addition with 2, so None

b = a ** 2
print(b.grad_fn)
print(b.grad_fn.next_functions)

c = b + 3
print(c.grad_fn)

y = c.mean()
print(y.grad_fn)

((<AccumulateGrad object at 0x7a47c5658fa0>, 0), (None, 0))
((<AddBackward0 object at 0x7a47c55e39a0>, 0),)


In [75]:
y.backward()

In [76]:
print(x.grad)

tensor([2.6667, 4.0000, 5.3333])


In [104]:
def walk(fn):
    if fn is None:
        return
    print(type(fn).__name__)

    for grad, _ in fn.next_functions:
        walk(grad)


walk(y.grad_fn)

MeanBackward0
AddBackward0
PowBackward0
AddBackward0
AccumulateGrad


In [112]:
# Even if u combine two operations, internally pytorch creates additionally nodes for each individual operations.
# i.e. PyTorch builds the graph from operations..
a = (x + 2) ** 2
print(a.grad_fn) # PowBackward
print(a.grad_fn.next_functions) # AddBackward

c = b + 3
print(c.grad_fn)
y = c.mean()
print(y.grad_fn)

((<AddBackward0 object at 0x7a47c56e8c70>, 0),)


In [108]:
walk(y.grad_fn)

MeanBackward0
AddBackward0
PowBackward0
AddBackward0
AccumulateGrad
